# Generated by Django 3.0 on 2020-11-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_of_birth', models.DateField()),
                ('matric_no', models.CharField(max_length=16)),
                ('fingerprint', models.ImageField(upload_to='<django.db.models.fields.CharField>/finger-print')),
                ('profile_pic', models.ImageField(upload_to='<django.db.models.fields.CharField>/profile-pic')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('where', models.CharField(default='FSSE', max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acs.Student')),
            ],
        ),
    ]
