# Generated by Django 3.0 on 2020-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fingerprint',
            field=models.ImageField(upload_to='finger-print'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='profile-pic'),
        ),
    ]
