# Generated by Django 3.0 on 2020-11-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_auto_20201105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
