# Generated by Django 3.0 on 2020-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0003_auto_20201105_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fprint_base64',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
