# Generated by Django 3.0 on 2020-11-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0004_student_fprint_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fprint_base64',
            field=models.TextField(),
        ),
    ]
